# Generated by Django 4.0.4 on 2022-05-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spytnik', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='av_score',
        ),
        migrations.CreateModel(
            name='PostDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='articles/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spytnik.post')),
            ],
        ),
    ]
