# Generated by Django 4.0.4 on 2022-05-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spytnik', '0004_remove_post_av_score_postdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdescription',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
