# Generated by Django 4.0.4 on 2022-05-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spytnik', '0005_postdescription_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=25),
        ),
    ]
