# Generated by Django 4.0.4 on 2022-05-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spytnik', '0006_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdescription',
            old_name='author',
            new_name='belong',
        ),
    ]
