# Generated by Django 4.0.4 on 2022-05-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spytnik', '0007_rename_author_postdescription_belong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdescription',
            name='belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='description', to='spytnik.post'),
        ),
    ]
