# Generated by Django 4.0.4 on 2022-05-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spytnik', '0009_pleb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pleb',
            name='registration_date',
        ),
    ]
