# Generated by Django 4.0.4 on 2022-05-28 03:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spytnik', '0010_remove_pleb_registration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voted_on',
            new_name='voted_date',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'book')},
        ),
    ]
