# Generated by Django 4.0.4 on 2022-05-28 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spytnik', '0012_alter_vote_unique_together_vote_post_alter_vote_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
