# Generated by Django 4.0.4 on 2022-05-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spytnik', '0015_alter_vote_post_alter_vote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
