# Generated by Django 4.0.4 on 2022-05-31 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spytnik', '0017_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
